import React, { createContext, useContext, useState } from 'react';

const TRANSLATIONS = {
  en: {
    appName: 'Krishi',
    tagline: 'Smart Crop Advisory System',
    dashboard: 'Dashboard',
    cropAdvisor: 'Crop Advisor',
    fertilizerGuide: 'Fertilizer Guide',
    weather: 'Weather',
    diseaseDetector: 'Disease Detector',
    marketPrices: 'Market Prices',
    voiceAssistant: 'Voice Assistant',
    submit: 'Submit',
    loading: 'Loading...',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    ph: 'Soil pH',
    temperature: 'Temperature (°C)',
    humidityLabel: 'Humidity (%)',
    rainfall: 'Rainfall (mm)',
    getRecommendation: 'Get Recommendation',
    cropRecommended: 'Recommended Crop',
    confidence: 'Confidence',
    season: 'Season',
    water: 'Water Need',
    selectCrop: 'Select Crop',
    soilNitrogen: 'Soil Nitrogen (N)',
    soilPhosphorus: 'Soil Phosphorus (P)',
    soilPotassium: 'Soil Potassium (K)',
    area: 'Area (Hectares)',
    getFertilizer: 'Get Fertilizer Plan',
    uploadLeafLabel: 'Upload Leaf Image',
    dragDrop: 'Drag & drop or click to upload',
    analyzeDisease: 'Analyze Disease',
    detected: 'Detected Disease',
    treatment: 'Treatment',
    severity: 'Severity',
    enterCity: 'Enter City Name',
    checkWeather: 'Check Weather',
    feels: 'Feels Like',
    wind: 'Wind',
    cropName: 'Crop Name',
    districtName: 'District / City',
    forecastMonths: 'Forecast Months',
    getPrices: 'Get Price Forecast',
    currentPrice: 'Current Price',
    priceAdvice: 'Market Advice',
    msp: 'MSP (Min. Support Price)',
    welcomeBack: 'Welcome to Krishi',
    welcomeMsg: 'Your AI-powered farming companion',
    explore: 'Explore',
    quickActions: 'Quick Actions',
    todayWeather: "Today's Weather",
    talkToUs: 'Tap mic & speak your query',
    tipOfDay: 'Tip of the Day',
    alternate: 'Other Possibilities',
    healthy: 'Plant Appears Healthy!',
    healthyMsg: 'No major disease detected. Keep monitoring your crops regularly.',
    soilParams: 'Soil Parameters',
    climateCond: 'Climate Conditions',
    getAiRec: 'Get AI Recommendation',
    analyzing: 'Analyzing...',
    topRec: 'Top Recommendation',
    soilSuggestions: 'Suggestions for Your Soil',
    serverError: 'Cannot reach server. Please try again later.',
    advisorSubtitle: 'Our AI analyzes your soil and climate data to suggest the most profitable crops.',
    welcome: 'Welcome back',
    farmStatus: 'Here is what\'s happening on your farm today.',
    soilHealth: 'Soil Health Score',
    soilTrend: '↑ 4% from last test',
    priceTrendRice: 'Price Trend (Rice)',
    priceTrendUp: '↑ 2.4% this week',
    aiCropMatch: 'AI Crop Match',
    optimalRice: 'Optimal: Rice',
    aiInsights: 'AI Smart Insights',
    agriTip: 'Agricultural Tip',
    rainTip: 'Rain expected in 48 hours — consider delaying scheduled irrigation to save water.',
    disAlert: 'Disease Alert',
    humidityAlert: 'High humidity levels detected. Monitor Rice fields for Bacterial Leaf Blight.',
    analyzeSoil: 'Analyze Soil',
    detectDisease: 'Detect Disease',
    farmAnalytics: 'Your Farm Analytics',
    chartLoading: 'Interactive analytics chart rendering...',
    detectorSubtitle: 'Identify plant health issues instantly using our computer vision models.',
    captureAnalyze: 'Capture & Analyze',
    uploadLeaf: 'Drop leaf photo here',
    browseGallery: 'or click to browse from gallery',
    camera: 'Camera',
    diagnose: 'Diagnose Disease',
    howItWorks: 'How it works',
    howItWorksText: 'Our deep learning models are trained on over 50,000 images of infected crops. For best results:',
    tip1: 'Ensure the leaf is well-lit and in focus.',
    tip2: 'Place the leaf against a neutral background.',
    tip3: 'Focus on the infected part of the plant.',
    healthyTarget: 'Target looks healthy!',
    noSymptoms: 'No symptoms of common diseases detected. Keep up the good work!',
    aiConfidence: 'AI Confidence',
    primarySymptoms: 'Primary Symptoms',
    treatmentPlan: 'Treatment Plan',
    affectedCrops: 'Affected Crops',
    severityLabel: 'SEVERITY',
    marketSubtitle: 'AI-powered price forecasting to help you time your harvest for maximum profit.',
    generateForecast: 'Generate Market Forecast',
    calculating: 'Calculating...',
    sixMonthTrend: '6-Month Trend',
    marketStatus: 'Market Status',
    bullish: 'BULLISH 🐂',
    bearish: 'BEARISH 🐻',
    highDemand: 'High Demand',
    priceProj: 'Price Projection',
    marketAdviceText: 'Market Advisory',
    recStrategy: 'Recommended Strategy:',
    staggeredSell: 'Consider staggered selling over the next 3 months to normalize price volatility.',
    perQuintal: 'Per Quintal',
    guaranteed: 'Guaranteed',
    weatherSubtitle: 'Real-time local weather insights for smarter farming decisions.',
    searchCity: 'Search city...',
    search: 'Search',
    currentForecast: 'Current Forecast',
    today: 'TODAY',
    next7Days: 'Next 7 Days',
    smartAdvisory: 'Smart Farming Advisory',
    optimalConditions: 'Optimal Conditions',
    optimalText: 'The next 48 hours are ideal for pesticide application. Winds are low and no immediate rainfall is predicted.',
    irrigationAlert: 'Irrigation Alert',
    irrigationText: 'Humidity levels are rising. Adjust your irrigation schedule to prevent fungal growth in susceptible crops.',
    humidity: 'HUMIDITY',
    windSpeed: 'WIND SPEED',
    needHelp: 'Need help?',
    supportText: 'Contact our agri-experts anytime.',
    support: 'Support',
    systemStatus: 'System Status',
    backendLabel: 'Backend',
    backendMatch: 'Ensure this matches your Render URL',
  },
  hi: {
    appName: 'कृषि',
    tagline: 'स्मार्ट फसल परामर्श प्रणाली',
    dashboard: 'डैशबोर्ड',
    cropAdvisor: 'फसल सलाहकार',
    fertilizerGuide: 'खाद गाइड',
    weather: 'मौसम',
    diseaseDetector: 'रोग पहचान',
    marketPrices: 'बाज़ार भाव',
    voiceAssistant: 'आवाज़ सहायक',
    submit: 'जमा करें',
    loading: 'लोड हो रहा है...',
    nitrogen: 'नाइट्रोजन (N)',
    phosphorus: 'फॉस्फोरस (P)',
    potassium: 'पोटेशियम (K)',
    ph: 'मिट्टी pH',
    temperature: 'तापमान (°C)',
    humidityLabel: 'आर्द्रता (%)',
    rainfall: 'वर्षा (मिमी)',
    getRecommendation: 'सिफारिश पाएं',
    cropRecommended: 'अनुशंसित फसल',
    confidence: 'विश्वास',
    season: 'मौसम',
    water: 'पानी की जरूरत',
    selectCrop: 'फसल चुनें',
    soilNitrogen: 'मिट्टी नाइट्रोजन',
    soilPhosphorus: 'मिट्टी फॉस्फोरस',
    soilPotassium: 'मिट्टी पोटेशियम',
    area: 'क्षेत्र (हेक्टेयर)',
    getFertilizer: 'खाद योजना पाएं',
    uploadLeafLabel: 'पत्ती की फोटो अपलोड करें',
    dragDrop: 'खींचें या क्लिक करें',
    analyzeDisease: 'रोग की जांच करें',
    detected: 'पहचाना गया रोग',
    treatment: 'उपचार',
    severity: 'गंभीरता',
    enterCity: 'शहर का नाम दर्ज करें',
    checkWeather: 'मौसम जांचें',
    feels: 'महसूस होता है',
    wind: 'हवा',
    cropName: 'फसल का नाम',
    districtName: 'जिला / शहर',
    forecastMonths: 'पूर्वानुमान महीने',
    getPrices: 'मूल्य पूर्वानुमान पाएं',
    currentPrice: 'वर्तमान मूल्य',
    priceAdvice: 'बाज़ार सलाह',
    msp: 'एमएसपी (न्यूनतम समर्थन मूल्य)',
    welcomeBack: 'कृषि में आपका स्वागत है',
    welcomeMsg: 'आपका AI खेती सहायक',
    explore: 'एक्सप्लोर करें',
    quickActions: 'त्वरित क्रियाएं',
    todayWeather: 'आज का मौसम',
    talkToUs: 'माइक दबाएं और बोलें',
    tipOfDay: 'आज की सलाह',
    alternate: 'अन्य संभावनाएं',
    healthy: 'पौधा स्वस्थ दिखता है!',
    healthyMsg: 'कोई बड़ी बीमारी नहीं मिली। नियमित निगरानी जारी रखें।',
    soilParams: 'मिट्टी के मापदंड',
    climateCond: 'जलवायु की स्थिति',
    getAiRec: 'AI सिफारिश पाएं',
    analyzing: 'जांच हो रही है...',
    topRec: 'शीर्ष सिफारिश',
    soilSuggestions: 'आपकी मिट्टी के लिए सुझाव',
    serverError: 'सर्वर तक नहीं पहुँच पा रहे हैं। कृपया बाद में प्रयास करें।',
    advisorSubtitle: 'हमारा AI आपकी मिट्टी और जलवायु डेटा का विश्लेषण करता है ताकि सबसे लाभदायक फसलों का सुझाव दिया जा सके।',
    welcome: 'स्वागत है',
    farmStatus: 'आज आपके खेत में क्या हो रहा है, यहाँ देखें।',
    soilHealth: 'मिट्टी स्वास्थ्य स्कोर',
    soilTrend: '↑ पिछले परीक्षण से 4% अधिक',
    priceTrendRice: 'मूल्य प्रवृत्ति (चावल)',
    priceTrendUp: '↑ इस सप्ताह 2.4%',
    aiCropMatch: 'AI फसल मिलान',
    optimalRice: 'इष्टतम: चावल',
    aiInsights: 'AI स्मार्ट अंतर्दृष्टि',
    agriTip: 'कृषि सलाह',
    rainTip: '48 घंटों में बारिश की संभावना है - पानी बचाने के लिए सिंचाई टालने पर विचार करें।',
    disAlert: 'रोग चेतावनी',
    humidityAlert: 'उच्च आर्द्रता स्तर का पता चला। बैक्टीरिया लीफ ब्लाइट के लिए चावल के खेतों की निगरानी करें।',
    analyzeSoil: 'मिट्टी विश्लेषण',
    detectDisease: 'रोग पहचानें',
    farmAnalytics: 'आपके खेत का विश्लेषण',
    chartLoading: 'इंटरएक्टिव विश्लेषण चार्ट लोड हो रहा है...',
    detectorSubtitle: 'हमारे कंप्यूटर विजन मॉडल का उपयोग करके पौधों की स्वास्थ्य समस्याओं की तुरंत पहचान करें।',
    captureAnalyze: 'कैप्चर और विश्लेषण',
    uploadLeaf: 'पत्ती की फोटो यहाँ डालें',
    browseGallery: 'या गैलरी से ब्राउज़ करने के लिए क्लिक करें',
    camera: 'कैमरा',
    diagnose: 'रोग का निदान करें',
    howItWorks: 'यह कैसे काम करता है',
    howItWorksText: 'हमारे गहन शिक्षण मॉडल संक्रमित फसलों की 50,000 से अधिक छवियों पर प्रशिक्षित हैं। सर्वोत्तम परिणामों के लिए:',
    tip1: 'सुनिश्चित करें कि पत्ती अच्छी तरह से प्रकाशित और फोकस में है।',
    tip2: 'पत्ती को एक तटस्थ पृष्ठभूमि पर रखें।',
    tip3: 'पौधे के संक्रमित हिस्से पर ध्यान दें।',
    healthyTarget: 'पौधा स्वस्थ दिखता है!',
    noSymptoms: 'सामान्य रोगों के कोई लक्षण नहीं मिले। अच्छा काम जारी रखें!',
    aiConfidence: 'AI विश्वास',
    primarySymptoms: 'प्राथमिक लक्षण',
    treatmentPlan: 'उपचार योजना',
    affectedCrops: 'प्रभावित फसलें',
    severityLabel: 'गंभीरता',
    marketSubtitle: 'अपनी फसल काटने का सही समय तय करने और अधिकतम लाभ पाने के लिए AI-संचालित मूल्य पूर्वानुमान।',
    generateForecast: 'बाज़ार पूर्वानुमान जनरेट करें',
    calculating: 'गणना हो रही है...',
    sixMonthTrend: '6 महीने की प्रवृत्ति',
    marketStatus: 'बाज़ार की स्थिति',
    bullish: 'तेजी 🐂',
    bearish: 'मंदी 🐻',
    highDemand: 'उच्च मांग',
    priceProj: 'मूल्य प्रक्षेपण',
    marketAdviceText: 'बाज़ार सलाह',
    recStrategy: 'अनुशंसित रणनीति:',
    staggeredSell: 'मूल्य अस्थिरता को सामान्य करने के लिए अगले 3 महीनों में चरणबद्ध बिक्री पर विचार करें।',
    perQuintal: 'प्रति क्विंटल',
    guaranteed: 'गारंटीकृत',
    weatherSubtitle: 'बेहतर खेती के निर्णयों के लिए वास्तविक समय में स्थानीय मौसम की जानकारी।',
    searchCity: 'शहर खोजें...',
    search: 'खोजें',
    currentForecast: 'वर्तमान पूर्वानुमान',
    today: 'आज',
    next7Days: 'अगले 7 दिन',
    smartAdvisory: 'स्मार्ट खेती सलाह',
    optimalConditions: 'इष्टतम स्थितियां',
    optimalText: 'अगले 48 घंटे कीटनाशकों के छिड़काव के लिए आदर्श हैं। हवा कम है और तत्काल बारिश की भविष्यवाणी नहीं की गई है।',
    irrigationAlert: 'सिंचाई अलर्ट',
    irrigationText: 'आर्द्रता का स्तर बढ़ रहा है। संवेदनशील फसलों में कवक के विकास को रोकने के लिए अपने सिंचाई कार्यक्रम को समायोजित करें।',
    humidity: 'आर्द्रता',
    windSpeed: 'हवा की गति',
    needHelp: 'क्या आपको मदद चाहिए?',
    supportText: 'किसी भी समय हमारे कृषि विशेषज्ञों से संपर्क करें।',
    support: 'सपोर्ट',
    systemStatus: 'सिस्टम स्थिति',
    backendLabel: 'बैकएंड',
    backendMatch: 'सुनिश्चित करें कि यह आपके Render URL से मेल खाता है',
  },
  kn: {
    appName: 'ಕೃಷಿ',
    tagline: 'ಸ್ಮಾರ್ಟ್ ಬೆಳೆ ಸಲಹಾ ವ್ಯವಸ್ಥೆ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    cropAdvisor: 'ಬೆಳೆ ಸಲಹೆಗಾರ',
    fertilizerGuide: 'ಗೊಬ್ಬರ ಮಾರ್ಗದರ್ಶಿ',
    weather: 'ಹವಾಮಾನ',
    diseaseDetector: 'ರೋಗ ಪತ್ತೆ',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
    voiceAssistant: 'ಧ್ವನಿ ಸಹಾಯಕ',
    submit: 'ಸಲ್ಲಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    nitrogen: 'ನೈಟ್ರೋಜನ್ (N)',
    phosphorus: 'ಫಾಸ್ಫರಸ್ (P)',
    potassium: 'ಪೊಟ್ಯಾಸಿಯಮ್ (K)',
    ph: 'ಮಣ್ಣಿನ pH',
    temperature: 'ತಾಪಮಾನ (°C)',
    humidityLabel: 'ಆರ್ದ್ರತೆ (%)',
    rainfall: 'ಮಳೆ (ಮಿಮಿ)',
    getRecommendation: 'ಶಿಫಾರಸು ಪಡೆಯಿರಿ',
    cropRecommended: 'ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆ',
    confidence: 'ವಿಶ್ವಾಸ',
    season: 'ಋತು',
    water: 'ನೀರಿನ ಅವಶ್ಯಕತೆ',
    selectCrop: 'ಬೆಳೆ ಆಯ್ಕೆ ಮಾಡಿ',
    soilNitrogen: 'ಮಣ್ಣಿನ ನೈಟ್ರೋಜನ್',
    soilPhosphorus: 'ಮಣ್ಣಿನ ಫಾಸ್ಫರಸ್',
    soilPotassium: 'ಮಣ್ಣಿನ ಪೊಟ్యాಸಿಯಮ್',
    area: 'ಪ್ರದೇಶ (ಹೆಕ್ಟೇರ್)',
    getFertilizer: 'ಗೊಬ್ಬರ ಯೋಜನೆ ಪಡೆಯಿರಿ',
    uploadLeafLabel: 'ಎಲೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dragDrop: 'ಎಳೆಯಿರಿ ಅಥವಾ ಕ್ಲಿಕ್ ಮಾಡಿ',
    analyzeDisease: 'ರೋಗ ಪರೀಕ್ಷಿಸಿ',
    detected: 'ಪತ್ತೆಯಾದ ರೋಗ',
    treatment: 'ಚಿಕಿತ್ಸೆ',
    severity: 'ತೀವ್ರತೆ',
    enterCity: 'ನಗರ ಹೆಸರು ನಮೂದಿಸಿ',
    checkWeather: 'ಹವಾಮಾನ ಪರಿಶೀಲಿಸಿ',
    feels: 'ಅನಿಸುತ್ತದೆ',
    wind: 'ಗಾಳಿ',
    cropName: 'ಬೆಳೆ ಹೆಸರು',
    districtName: 'ಜಿಲ್ಲೆ / ನಗರ',
    forecastMonths: 'ಮುನ್ಸೂಚನೆ ತಿಂಗಳುಗಳು',
    getPrices: 'ಬೆಲೆ ಮುನ್ಸೂಚನೆ ಪಡೆಯಿರಿ',
    currentPrice: 'ಪ್ರಸ್ತುತ ಬೆಲೆ',
    priceAdvice: 'ಮಾರುಕಟ್ಟೆ ಸಲಹೆ',
    msp: 'MSP (ಕನಿಷ್ಠ ಬೆಂಬಲ ಬೆಲೆ)',
    welcomeBack: 'ಕೃಷಿಗೆ ಸ್ವಾಗತ',
    welcomeMsg: 'ನಿಮ್ಮ AI ಕೃಷಿ ಸಂಗಾತಿ',
    explore: 'ಅನ್ವೇಷಿಸಿ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    todayWeather: 'ಇಂದಿನ ಹವಾಮಾನ',
    talkToUs: 'ಮೈಕ್ ಒತ್ತಿ ಮಾತನಾಡಿ',
    tipOfDay: 'ಇಂದಿನ ಸಲಹೆ',
    alternate: 'ಇತರ ಸಾಧ್ಯತೆಗಳು',
    healthy: 'ಸಸ್ಯ ಆರೋಗ್ಯಕರವಾಗಿದೆ!',
    healthyMsg: 'ಯಾವುದೇ ದೊಡ್ಡ ರೋಗ ಕಂಡುಬಂದಿಲ್ಲ. ನಿಯಮಿತ ನಿಗಾ ಇರಿಸಿ.',
    soilParams: 'ಮಣ್ಣಿನ ನಿಯತಾಂಕಗಳು',
    climateCond: 'ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿಗಳು',
    getAiRec: 'AI ಶಿಫಾರಸು ಪಡೆಯಿರಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    topRec: 'ಉನ್ನತ ಶಿಫಾರಸು',
    soilSuggestions: 'ನಿಮ್ಮ ಮಣ್ಣಿಗೆ ಸಲಹೆಗಳು',
    serverError: 'ಸರ್ವರ್ ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    advisorSubtitle: 'ಅತ್ಯಂತ ಲಾಭದಾಯಕ ಬೆಳೆಗಳನ್ನು ಸೂಚಿಸಲು ನಮ್ಮ AI ನಿಮ್ಮ ಮಣ್ಣು ಮತ್ತು ಹವಾಮಾನ ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.',
    welcome: 'ಸ್ವಾಗತ',
    farmStatus: 'ಇಂದು ನಿಮ್ಮ ಜಮೀನಿನಲ್ಲಿ ಏನಾಗುತ್ತಿದೆ ಎಂಬುದು ಇಲ್ಲಿದೆ.',
    soilHealth: 'ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಸ್ಕೋರ್',
    soilTrend: '↑ ಕಳೆದ ಪರೀಕ್ಷೆಗಿಂತ 4% ಹೆಚ್ಚಳ',
    priceTrendRice: 'ಬೆಲೆ ಪ್ರವೃತ್ತಿ (ಅಕ್ಕಿ)',
    priceTrendUp: '↑ ಈ ವಾರ 2.4% ಹೆಚ್ಚಳ',
    aiCropMatch: 'AI ಬೆಳೆ ಹೊಂದಾಣಿಕೆ',
    optimalRice: 'ಸೂಕ್ತ: ಅಕ್ಕಿ',
    aiInsights: 'AI ಸ್ಮಾರ್ಟ್ ಒಳನೋಟಗಳು',
    agriTip: 'ಕೃಷಿ ಸಲಹೆ',
    rainTip: '48 ಗಂಟೆಗಳಲ್ಲಿ ಮಳೆಯ ನಿರೀಕ್ಷೆಯಿದೆ - ನೀರನ್ನು ಉಳಿಸಲು ನಿಗದಿತ ನೀರಾವರಿಯನ್ನು ಮುಂದೂಡುವುದನ್ನು ಪರಿಗಣಿಸಿ.',
    disAlert: 'ರೋಗದ ಎಚ್ಚರಿಕೆ',
    humidityAlert: 'ಹೆಚ್ಚಿನ ಆರ್ದ್ರತೆಯ ಮಟ್ಟಗಳು ಪತ್ತೆಯಾಗಿವೆ. ಬ್ಯಾಕ್ಟೀರಿಯಾದ ಎಲೆ ಬ್ಲೈಟ್‌ಗಾಗಿ ಅಕ್ಕಿ ಗದ್ದೆಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.',
    analyzeSoil: 'ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆ',
    detectDisease: 'ರೋಗ ಪತ್ತೆಹಚ್ಚಿ',
    farmAnalytics: 'ನಿಮ್ಮ ಜಮೀನಿನ ವಿಶ್ಲೇಷಣೆ',
    chartLoading: 'ಸಂವಾದಾತ್ಮಕ ವಿಶ್ಲೇಷಣೆ ಚಾರ್ಟ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    detectorSubtitle: 'ನಮ್ಮ ಕಂಪ್ಯೂಟರ್ ವಿಷನ್ ಮಾಡೆಲ್‌ಗಳನ್ನು ಬಳಸಿಕೊಂಡು ಸಸ್ಯದ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳನ್ನು ತಕ್ಷಣವೇ ಗುರುತಿಸಿ.',
    captureAnalyze: 'ಕ್ಯಾಪ್ಚರ್ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',
    uploadLeaf: 'ಎಲೆ ಫೋಟೋವನ್ನು ಇಲ್ಲಿಗೆ ಎಳೆಯಿರಿ',
    browseGallery: 'ಅಥವಾ ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    camera: 'ಕ್ಯಾಮೆರಾ',
    diagnose: 'ರೋಗದ ಪತ್ತೆ',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    howItWorksText: 'ನಮ್ಮ ಡೀಪ್ ಲರ್ನಿಂಗ್ ಮಾಡೆಲ್‌ಗಳು ಸೋಂಕಿತ ಬೆಳೆಗಳ 50,000 ಕ್ಕೂ ಹೆಚ್ಚು ಚಿತ್ರಗಳ ಮೇಲೆ ತರಬೇತಿ ಪಡೆದಿವೆ. ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ:',
    tip1: 'ಎಲೆಯು ಚೆನ್ನಾಗಿ ಬೆಳಗಿದೆಯೆ ಮತ್ತು ಫೋಕಸ್‌ ನಲ್ಲಿದೆಯೇ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
    tip2: 'ಎಲೆಯನ್ನು ತಟಸ್ಥ ಹಿನ್ನೆಲೆಯ ಎದುರು ಇರಿಸಿ.',
    tip3: 'ಸಸ್ಯದ ಸೋಂಕಿತ ಭಾಗದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿ.',
    healthyTarget: 'ಸಸ್ಯವು ಆರೋಗ್ಯಕರವಾಗಿ ಕಾಣುತ್ತಿದೆ!',
    noSymptoms: 'ಸಾಮಾನ್ಯ ರೋಗಗಳ ಯಾವುದೇ ಲಕ್ಷಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಉತ್ತಮ ಕೆಲಸವನ್ನು ಮುಂದುವರಿಸಿ!',
    aiConfidence: 'AI ವಿಶ್ವಾಸ',
    primarySymptoms: 'ಪ್ರಾಥಮಿಕ ಲಕ್ಷಣಗಳು',
    treatmentPlan: 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆ',
    affectedCrops: 'ಪೀಡಿತ ಬೆಳೆಗಳು',
    severityLabel: 'ತೀವ್ರತೆ',
    marketSubtitle: 'ನಿಮ್ಮ ಸುಗ್ಗಿಯ ಸಮಯವನ್ನು ಸರಿಯಾಗಿ ನಿರ್ಧರಿಸಿ ಗರಿಷ್ಠ ಲಾಭ ಪಡೆಯಲು AI-ಚಾಲಿತ ಬೆಲೆ ಮುನ್ಸೂಚನೆ.',
    generateForecast: 'ಮಾರುಕಟ್ಟೆ ಮುನ್ಸೂಚನೆ ರಚಿಸಿ',
    calculating: 'ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತಿದೆ...',
    sixMonthTrend: '6 ತಿಂಗಳ ಪ್ರವೃತ್ತಿ',
    marketStatus: 'ಮಾರುಕಟ್ಟೆ ಸ್ಥಿತಿ',
    bullish: 'ಏರಿಕೆ 🐂',
    bearish: 'ಇಳಿಕೆ 🐻',
    highDemand: 'ಹೆಚ್ಚಿನ ಬೇಡಿಕೆ',
    priceProj: 'ಬೆಲೆ ಪ್ರಕ್ಷೇಪಣ',
    marketAdviceText: 'ಮಾರುಕಟ್ಟೆ ಸಲಹೆ',
    recStrategy: 'ಶಿಫಾರಸು ಮಾಡಿದ ತಂತ್ರ:',
    staggeredSell: 'ಬೆಲೆ ಅಸ್ಥಿರತೆಯನ್ನು ಸಮತೋಲನಗೊಳಿಸಲು ಮುಂದಿನ 3 ತಿಂಗಳಲ್ಲಿ ಹಂತ ಹಂತವಾಗಿ ಮಾರಾಟ ಮಾಡುವುದನ್ನು ಪರಿಗಣಿಸಿ.',
    perQuintal: 'ಪ್ರತಿ ಕ್ವಿಂಟಾಲ್',
    guaranteed: 'ಖಾತರಿ ಅವಧಿ',
    weatherSubtitle: 'ಚುರುಕಾದ ಕೃಷಿ ನಿರ್ಧಾರಗಳಿಗಾಗಿ ನೈಜ-ಸಮಯದ ಸ್ಥಳೀಯ ಹವಾಮಾನ ಒಳನೋಟಗಳು.',
    searchCity: 'ನಗರವನ್ನು ಹುಡುಕಿ...',
    search: 'ಹುಡುಕು',
    currentForecast: 'ಪ್ರಸ್ತುತ ಮುನ್ಸೂಚನೆ',
    today: 'ಇಂದು',
    next7Days: 'ಮುಂದಿನ 7 ದಿನಗಳು',
    smartAdvisory: 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಲಹೆ',
    optimalConditions: 'ಅತ್ಯುತ್ತಮ ಪರಿಸ್ಥಿತಿಗಳು',
    optimalText: 'ಮುಂದಿನ 48 ಗಂಟೆಗಳು ಕೀಟನಾಶಕ ಸಿಂಪಡಣೆಗೆ ಸೂಕ್ತವಾಗಿವೆ. ಗಾಳಿ ಕಡಿಮೆಯಿದೆ ಮತ್ತು ತಕ್ಷಣದ ಮಳೆಯ ಮುನ್ಸೂಚನೆ ಇಲ್ಲ.',
    irrigationAlert: 'ನೀರಾವರಿ ಎಚ್ಚರಿಕೆ',
    irrigationText: 'ಆರ್ದ್ರತೆಯ ಮಟ್ಟಗಳು ಹೆಚ್ಚುತ್ತಿವೆ. ಬೆಳೆಗಳಲ್ಲಿ ಶಿಲೀಂಧ್ರಗಳ ಬೆಳವಣಿಗೆಯನ್ನು ತಡೆಗಟ್ಟಲು ನಿಮ್ಮ ನೀರಾವರಿ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಹೊಂದಿಸಿ.',
    humidity: 'ಆರ್ದ್ರತೆ',
    windSpeed: 'ಗಾಳಿಯ ವೇಗ',
    needHelp: 'ಸಹಾಯ ಬೇಕೇ?',
    supportText: 'ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ನಮ್ಮ ಕೃಷಿ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    support: 'ಬೆಂಬಲ',
    systemStatus: 'ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ',
    backendLabel: 'ಬ್ಯಾಕೆಂಡ್',
    backendMatch: 'ಇದು ನಿಮ್ಮ Render URL ಗೆ ಹೊಂದಿಕೆಯಾಗಿದೆಯೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ',
  },
  te: {
    appName: 'కృషి',
    tagline: 'స్మార్ట్ పంట సలహా వ్యవస్థ',
    dashboard: 'డాష్‌బోర్డ్',
    cropAdvisor: 'పంట సలహాదారు',
    fertilizerGuide: 'ఎరువుల గైడ్',
    weather: 'వాతావరణం',
    diseaseDetector: 'వ్యాధి గుర్తింపు',
    marketPrices: 'మార్కెట్ ధరలు',
    voiceAssistant: 'వాయిస్ అసిస్టెంట్',
    submit: 'సమర్పించండి',
    loading: 'లోడ్ అవుతోంది...',
    nitrogen: 'నైట్రోజన్ (N)',
    phosphorus: 'ఫాస్ఫరస్ (P)',
    potassium: 'పొటాషియం (K)',
    ph: 'నేల pH',
    temperature: 'ఉష్ణోగ్రత (°C)',
    humidity: 'తేమ (%)',
    rainfall: 'వర్షపాతం (మిమీ)',
    getRecommendation: 'సిఫార్సు పొందండి',
    cropRecommended: 'సిఫార్సు చేయబడిన పంట',
    confidence: 'విశ్వాసం',
    season: 'సీజన్',
    water: 'నీటి అవసరం',
    selectCrop: 'పంటను ఎంచుకోండి',
    soilNitrogen: 'నేల నైట్రోజన్',
    soilPhosphorus: 'నేల ఫాస్ఫరస్',
    soilPotassium: 'నేల పొటాషియం',
    area: 'విస్తీర్ణం (హెక్టార్లు)',
    getFertilizer: 'ఎరువుల పథకం పొందండి',
    uploadLeaf: 'ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి',
    dragDrop: 'లాగండి లేదా క్లిక్ చేయండి',
    analyzeDisease: 'వ్యాధిని పరీక్షించండి',
    detected: 'గుర్తించబడిన వ్యాధి',
    treatment: 'చికిత్స',
    severity: 'తీవ్రత',
    enterCity: 'నగరం పేరు నమోదు చేయండి',
    checkWeather: 'వాతావరణం చెక్ చేయండి',
    feels: 'అనిపిస్తోంది',
    wind: 'గాలి',
    cropName: 'పంట పేరు',
    districtName: 'జిల్లా / నగరం',
    forecastMonths: 'అంచనా నెలలు',
    getPrices: 'ధర అంచనా పొందండి',
    currentPrice: 'ప్రస్తుత ధర',
    priceAdvice: 'మార్కెట్ సలహా',
    msp: 'MSP (కనిష్ఠ మద్దతు ధర)',
    welcomeBack: 'కృషికి స్వాగతం',
    welcomeMsg: 'మీ AI వ్యవసాయ సహచరుడు',
    explore: 'అన్వేషించండి',
    quickActions: 'త్వరిత చర్యలు',
    todayWeather: 'ఈరోజు వాతావరణం',
    talkToUs: 'మైక్ నొక్కి మాట్లాడండి',
    tipOfDay: 'ఈరోజు చిట్కా',
    alternate: 'ఇతర అవకాశాలు',
    healthy: 'మొక్క ఆరోగ్యంగా ఉంది!',
    healthyMsg: 'పెద్ద వ్యాధి కనుగొనబడలేదు. క్రమం తప్పకుండా పర్యవేక్షించండి.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, TRANSLATIONS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
