import React, { createContext, useContext, useState } from 'react';

const TRANSLATIONS = {
  en: {
    appName: 'Krishi',
    tagline: 'Smart Crop Advisory System',
    dashboard: 'Dashboard',
    cropAdvisor: 'Crop Advisor',
    fertilizerGuide: 'Fertilizer Guide',
    weather: 'Weather',
    diseaseDetector: 'Disease Detector',
    marketPrices: 'Market Prices',
    voiceAssistant: 'Voice Assistant',
    submit: 'Submit',
    loading: 'Loading...',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    ph: 'Soil pH',
    temperature: 'Temperature (°C)',
    humidity: 'Humidity (%)',
    rainfall: 'Rainfall (mm)',
    getRecommendation: 'Get Recommendation',
    cropRecommended: 'Recommended Crop',
    confidence: 'Confidence',
    season: 'Season',
    water: 'Water Need',
    selectCrop: 'Select Crop',
    soilNitrogen: 'Soil Nitrogen (N)',
    soilPhosphorus: 'Soil Phosphorus (P)',
    soilPotassium: 'Soil Potassium (K)',
    area: 'Area (Hectares)',
    getFertilizer: 'Get Fertilizer Plan',
    uploadLeaf: 'Upload Leaf Image',
    dragDrop: 'Drag & drop or click to upload',
    analyzeDisease: 'Analyze Disease',
    detected: 'Detected Disease',
    treatment: 'Treatment',
    severity: 'Severity',
    enterCity: 'Enter City Name',
    checkWeather: 'Check Weather',
    feels: 'Feels Like',
    wind: 'Wind',
    cropName: 'Crop Name',
    districtName: 'District / City',
    forecastMonths: 'Forecast Months',
    getPrices: 'Get Price Forecast',
    currentPrice: 'Current Price',
    priceAdvice: 'Market Advice',
    msp: 'MSP (Min. Support Price)',
    welcomeBack: 'Welcome to Krishi',
    welcomeMsg: 'Your AI-powered farming companion',
    explore: 'Explore',
    quickActions: 'Quick Actions',
    todayWeather: "Today's Weather",
    talkToUs: 'Tap mic & speak your query',
    tipOfDay: 'Tip of the Day',
    alternate: 'Other Possibilities',
    healthy: 'Plant Appears Healthy!',
    healthyMsg: 'No major disease detected. Keep monitoring your crops regularly.',
  },
  hi: {
    appName: 'कृषि',
    tagline: 'स्मार्ट फसल परामर्श प्रणाली',
    dashboard: 'डैशबोर्ड',
    cropAdvisor: 'फसल सलाहकार',
    fertilizerGuide: 'खाद गाइड',
    weather: 'मौसम',
    diseaseDetector: 'रोग पहचान',
    marketPrices: 'बाज़ार भाव',
    voiceAssistant: 'आवाज़ सहायक',
    submit: 'जमा करें',
    loading: 'लोड हो रहा है...',
    nitrogen: 'नाइट्रोजन (N)',
    phosphorus: 'फॉस्फोरस (P)',
    potassium: 'पोटेशियम (K)',
    ph: 'मिट्टी pH',
    temperature: 'तापमान (°C)',
    humidity: 'आर्द्रता (%)',
    rainfall: 'वर्षा (मिमी)',
    getRecommendation: 'सिफारिश पाएं',
    cropRecommended: 'अनुशंसित फसल',
    confidence: 'विश्वास',
    season: 'मौसम',
    water: 'पानी की जरूरत',
    selectCrop: 'फसल चुनें',
    soilNitrogen: 'मिट्टी नाइट्रोजन',
    soilPhosphorus: 'मिट्टी फॉस्फोरस',
    soilPotassium: 'मिट्टी पोटेशियम',
    area: 'क्षेत्र (हेक्टेयर)',
    getFertilizer: 'खाद योजना पाएं',
    uploadLeaf: 'पत्ती की फोटो अपलोड करें',
    dragDrop: 'खींचें या क्लिक करें',
    analyzeDisease: 'रोग की जांच करें',
    detected: 'पहचाना गया रोग',
    treatment: 'उपचार',
    severity: 'गंभीरता',
    enterCity: 'शहर का नाम दर्ज करें',
    checkWeather: 'मौसम जांचें',
    feels: 'महसूस होता है',
    wind: 'हवा',
    cropName: 'फसल का नाम',
    districtName: 'जिला / शहर',
    forecastMonths: 'पूर्वानुमान महीने',
    getPrices: 'मूल्य पूर्वानुमान पाएं',
    currentPrice: 'वर्तमान मूल्य',
    priceAdvice: 'बाज़ार सलाह',
    msp: 'एमएसपी (न्यूनतम समर्थन मूल्य)',
    welcomeBack: 'कृषि में आपका स्वागत है',
    welcomeMsg: 'आपका AI खेती सहायक',
    explore: 'एक्सप्लोर करें',
    quickActions: 'त्वरित क्रियाएं',
    todayWeather: 'आज का मौसम',
    talkToUs: 'माइक दबाएं और बोलें',
    tipOfDay: 'आज की सलाह',
    alternate: 'अन्य संभावनाएं',
    healthy: 'पौधा स्वस्थ दिखता है!',
    healthyMsg: 'कोई बड़ी बीमारी नहीं मिली। नियमित निगरानी जारी रखें।',
  },
  kn: {
    appName: 'ಕೃಷಿ',
    tagline: 'ಸ್ಮಾರ್ಟ್ ಬೆಳೆ ಸಲಹಾ ವ್ಯವಸ್ಥೆ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    cropAdvisor: 'ಬೆಳೆ ಸಲಹೆಗಾರ',
    fertilizerGuide: 'ಗೊಬ್ಬರ ಮಾರ್ಗದರ್ಶಿ',
    weather: 'ಹವಾಮಾನ',
    diseaseDetector: 'ರೋಗ ಪತ್ತೆ',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
    voiceAssistant: 'ಧ್ವನಿ ಸಹಾಯಕ',
    submit: 'ಸಲ್ಲಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    nitrogen: 'ನೈಟ್ರೋಜನ್ (N)',
    phosphorus: 'ಫಾಸ್ಫರಸ್ (P)',
    potassium: 'ಪೊಟ್ಯಾಸಿಯಮ್ (K)',
    ph: 'ಮಣ್ಣಿನ pH',
    temperature: 'ತಾಪಮಾನ (°C)',
    humidity: 'ಆರ್ದ್ರತೆ (%)',
    rainfall: 'ಮಳೆ (ಮಿಮಿ)',
    getRecommendation: 'ಶಿಫಾರಸು ಪಡೆಯಿರಿ',
    cropRecommended: 'ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆ',
    confidence: 'ವಿಶ್ವಾಸ',
    season: 'ಋತು',
    water: 'ನೀರಿನ ಅವಶ್ಯಕತೆ',
    selectCrop: 'ಬೆಳೆ ಆಯ್ಕೆ ಮಾಡಿ',
    soilNitrogen: 'ಮಣ್ಣಿನ ನೈಟ್ರೋಜನ್',
    soilPhosphorus: 'ಮಣ್ಣಿನ ಫಾಸ್ಫರಸ್',
    soilPotassium: 'ಮಣ್ಣಿನ ಪೊಟ್ಯಾಸಿಯಮ್',
    area: 'ಪ್ರದೇಶ (ಹೆಕ್ಟೇರ್)',
    getFertilizer: 'ಗೊಬ್ಬರ ಯೋಜನೆ ಪಡೆಯಿರಿ',
    uploadLeaf: 'ಎಲೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dragDrop: 'ಎಳೆಯಿರಿ ಅಥವಾ ಕ್ಲಿಕ್ ಮಾಡಿ',
    analyzeDisease: 'ರೋಗ ಪರೀಕ್ಷಿಸಿ',
    detected: 'ಪತ್ತೆಯಾದ ರೋಗ',
    treatment: 'ಚಿಕಿತ್ಸೆ',
    severity: 'ತೀವ್ರತೆ',
    enterCity: 'ನಗರ ಹೆಸರು ನಮೂದಿಸಿ',
    checkWeather: 'ಹವಾಮಾನ ಪರಿಶೀಲಿಸಿ',
    feels: 'ಅನಿಸುತ್ತದೆ',
    wind: 'ಗಾಳಿ',
    cropName: 'ಬೆಳೆ ಹೆಸರು',
    districtName: 'ಜಿಲ್ಲೆ / ನಗರ',
    forecastMonths: 'ಮುನ್ಸೂಚನೆ ತಿಂಗಳುಗಳು',
    getPrices: 'ಬೆಲೆ ಮುನ್ಸೂಚನೆ ಪಡೆಯಿರಿ',
    currentPrice: 'ಪ್ರಸ್ತುತ ಬೆಲೆ',
    priceAdvice: 'ಮಾರುಕಟ್ಟೆ ಸಲಹೆ',
    msp: 'MSP (ಕನಿಷ್ಠ ಬೆಂಬಲ ಬೆಲೆ)',
    welcomeBack: 'ಕೃಷಿಗೆ ಸ್ವಾಗತ',
    welcomeMsg: 'ನಿಮ್ಮ AI ಕೃಷಿ ಸಂಗಾತಿ',
    explore: 'ಅನ್ವೇಷಿಸಿ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    todayWeather: 'ಇಂದಿನ ಹವಾಮಾನ',
    talkToUs: 'ಮೈಕ್ ಒತ್ತಿ ಮಾತನಾಡಿ',
    tipOfDay: 'ಇಂದಿನ ಸಲಹೆ',
    alternate: 'ಇತರ ಸಾಧ್ಯತೆಗಳು',
    healthy: 'ಸಸ್ಯ ಆರೋಗ್ಯಕರವಾಗಿದೆ!',
    healthyMsg: 'ಯಾವುದೇ ದೊಡ್ಡ ರೋಗ ಕಂಡುಬಂದಿಲ್ಲ. ನಿಯಮಿತ ನಿಗಾ ಇರಿಸಿ.',
  },
  te: {
    appName: 'కృషి',
    tagline: 'స్మార్ట్ పంట సలహా వ్యవస్థ',
    dashboard: 'డాష్‌బోర్డ్',
    cropAdvisor: 'పంట సలహాదారు',
    fertilizerGuide: 'ఎరువుల గైడ్',
    weather: 'వాతావరణం',
    diseaseDetector: 'వ్యాధి గుర్తింపు',
    marketPrices: 'మార్కెట్ ధరలు',
    voiceAssistant: 'వాయిస్ అసిస్టెంట్',
    submit: 'సమర్పించండి',
    loading: 'లోడ్ అవుతోంది...',
    nitrogen: 'నైట్రోజన్ (N)',
    phosphorus: 'ఫాస్ఫరస్ (P)',
    potassium: 'పొటాషియం (K)',
    ph: 'నేల pH',
    temperature: 'ఉష్ణోగ్రత (°C)',
    humidity: 'తేమ (%)',
    rainfall: 'వర్షపాతం (మిమీ)',
    getRecommendation: 'సిఫార్సు పొందండి',
    cropRecommended: 'సిఫార్సు చేయబడిన పంట',
    confidence: 'విశ్వాసం',
    season: 'సీజన్',
    water: 'నీటి అవసరం',
    selectCrop: 'పంటను ఎంచుకోండి',
    soilNitrogen: 'నేల నైట్రోజన్',
    soilPhosphorus: 'నేల ఫాస్ఫరస్',
    soilPotassium: 'నేల పొటాషియం',
    area: 'విస్తీర్ణం (హెక్టార్లు)',
    getFertilizer: 'ఎరువుల పథకం పొందండి',
    uploadLeaf: 'ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి',
    dragDrop: 'లాగండి లేదా క్లిక్ చేయండి',
    analyzeDisease: 'వ్యాధిని పరీక్షించండి',
    detected: 'గుర్తించబడిన వ్యాధి',
    treatment: 'చికిత్స',
    severity: 'తీవ్రత',
    enterCity: 'నగరం పేరు నమోదు చేయండి',
    checkWeather: 'వాతావరణం చెక్ చేయండి',
    feels: 'అనిపిస్తోంది',
    wind: 'గాలి',
    cropName: 'పంట పేరు',
    districtName: 'జిల్లా / నగరం',
    forecastMonths: 'అంచనా నెలలు',
    getPrices: 'ధర అంచనా పొందండి',
    currentPrice: 'ప్రస్తుత ధర',
    priceAdvice: 'మార్కెట్ సలహా',
    msp: 'MSP (కనిష్ఠ మద్దతు ధర)',
    welcomeBack: 'కృషికి స్వాగతం',
    welcomeMsg: 'మీ AI వ్యవసాయ సహచరుడు',
    explore: 'అన్వేషించండి',
    quickActions: 'త్వరిత చర్యలు',
    todayWeather: 'ఈరోజు వాతావరణం',
    talkToUs: 'మైక్ నొక్కి మాట్లాడండి',
    tipOfDay: 'ఈరోజు చిట్కా',
    alternate: 'ఇతర అవకాశాలు',
    healthy: 'మొక్క ఆరోగ్యంగా ఉంది!',
    healthyMsg: 'పెద్ద వ్యాధి కనుగొనబడలేదు. క్రమం తప్పకుండా పర్యవేక్షించండి.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, TRANSLATIONS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
